version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3307"
    ports:
      - "3307:3307"    
    networks:
      - app-tier      
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql

  app:
    depends_on:
      - db
    build: .
    command: bash -c 'while !</dev/tcp/db/3307; do sleep 1; done; npm run dev'
    container_name: biblioteca
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - app-tier   

  migration:
    depends_on:
      - db
      - app
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - app-tier
    command: bash -c 'while !</dev/tcp/db/3307; do sleep 1; done; npm run typeorm migration:run'

volumes:
  db_data: